### PR TITLE
Added peter to the project

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by PeterBell** [comment]
Could you at least add *something*?

**Comment by githubteacher** [comment]
LGTM 👍

**Comment by githubteacher** [comment]
harry-potter-congrats

**Comment by aodrei** [comment]
Say something

**Comment by segalal** [comment]
something!

**Comment by DougWest** [comment]
https://github.com/jbridge8133

**Comment by jahoust** [comment]
Garbage

**Comment by apatnai** [comment]
Great Job Peter!

**Comment by jhakaas** [comment]
Please define sometihng

**Comment by brettlemoine** [comment]
http://www.disapprovallook.com/images/look.png

**Comment by aodrei** [comment]
Write Judith, write

**Comment by jbridge8133** [comment]
Hello Judith!  You'll really like this SOMETHING

**Comment by brettlemoine** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwj8vInNqIDOAhUFw2MKHViECvgQjRwIBw&url=http%3A%2F%2Fwww.disapprovallook.com%2F&psig=AFQjCNH67CxzIBWUy-I0rfyibIY8fsIkQg&ust=1469044832941771

**Comment by githubteacher** [comment]
Yeah - need something defined . . .

**Comment by DougWest** [comment]
Tim, go read this: https://github.com/githubteacher/tofork/pull/4/commits/5e7b95e1abfc38cefb308cc8ee4d069fc2a253ea

**Comment by PeterBell** [comment]
Hey @dougwest you can @ mention tim if you want to

**Comment by githubteacher** [comment]
LGTM 👍 let's 🚢 it

**Pull request merged**
