### PR TITLE
add satawil

### PR DESCRIPTION
**Pull request by satawil**
Add satawil to project

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey, I think this is a great idea 👍

**Comment by PeterBell** [comment]
harry-potter-congrats

**Comment by PeterBell** [comment]
Hey @brntbeer this is cool (in a class) - what do _you_ think?

**Comment by dalgibbard** [comment]
Where am I?

**Comment by brntbeer** [comment]
@PeterBell I agree! think it looks awesome.

I know this has shipped already, but PRs are great because the conversation can continue even though it's completed!

**Pull request merged**
