### PR TITLE
Added peter to the project

### PR DESCRIPTION
**Pull request by PeterBell**

### CODE REVIEW

**Comment by githubteacher** [comment]
Hmmm, could you at least add your full name to the file?

**Comment by githubteacher** [comment]
Cool re: name - what about tests?

**Comment by githubteacher** [comment]
Great - LGTM :+1: let's :ship: it!

**Comment by githubteacher** [comment]
harry-potter-congrats

**Comment by nenochs-iqn** [comment]
+1

**Comment by jad007** [comment]
something

**Comment by mullerpaul** [comment]
rock on!

**Comment by jkantola50** [comment]
BANANAS!

**Comment by hmajid** [comment]
hello!

**Comment by danhillenbrand** [comment]
Motorcycles rule

**Comment by mreddick99** [comment]
check 1 2

**Comment by erbocolo** [comment]
This change is f***ing METAL. \m/

**Comment by 1-3** [comment]
hi

**Comment by bdumitrescu** [comment]
yeeeaaa

**Comment by nenochs-iqn** [comment]
:+1:

**Comment by danhillenbrand** [comment]
:+1:

**Comment by rpacetti** [comment]
Smells bad :-1:

**Comment by jferr** [comment]
+1

**Comment by mullerpaul** [comment]
:+1:

**Comment by jkantola50** [comment]
:8ball:

**Comment by 1-3** [comment]
:+1:

**Comment by sshahiqn** [comment]
:+1:

**Comment by rgort** [comment]
}:->

**Comment by 1-3** [comment]
:100:
:1234:

**Comment by rpacetti** [comment]
acme

**Comment by rpacetti** [comment]
locutus

**Pull request merged**
